# Generated by Django 5.0.4 on 2024-04-28 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название задания')),
                ('description', models.CharField(max_length=600, verbose_name='Описание')),
                ('image', models.ImageField(upload_to='image_todo/', verbose_name='Фотография')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Статус выполнения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата задания')),
            ],
            options={
                'verbose_name': 'Список задач',
                'verbose_name_plural': 'Списки задач',
            },
        ),
    ]
